# Dockerfile.dev para Todo Service (Node.js)

FROM node:24-alpine

WORKDIR /app

RUN apk update && apk add --no-cache bash openssl libc6-compat

COPY services/todo-service/package*.json ./
COPY services/todo-service/tsconfig.json ./
COPY packages/common/package*.json ./packages/common/

RUN npm install

COPY services/todo-service/ .
COPY packages/common/ ./packages/common/

RUN chmod +x ./wait-for-it.sh
RUN find /app -type f -name "*.sh" -exec chmod +x {} \;

EXPOSE 3002

# CMD ["sh", "-c", "./wait-for-it.sh postgres:5432 -- npm run dev"]
