# Dockerfile.dev para Todo Service (Node.js)

FROM node:20-alpine

WORKDIR /app

RUN apk add --no-cache bash

# 1. Copiar manifests (Caminhos relativos à raiz do projeto)
COPY services/todo-service/package*.json ./
COPY services/todo-service/tsconfig.json ./
COPY packages/common/package*.json ./packages/common/

# 2. Executar o npm 
RUN npm install

# 3. Copiar código do serviço e da biblioteca
COPY services/todo-service/ .
COPY packages/common/ ./packages/common/

# 4. Scripts e Permissões
RUN chmod +x ./wait-for-it.sh
RUN find /app -type f -name "*.sh" -exec chmod +x {} \;

# Expor a porta
EXPOSE 3002

# Rodar hot reload com ts-node-dev
CMD ["sh", "-c", "./wait-for-it.sh postgres:5432 -- npm run dev"]
