# Dockerfile.dev para Notification Service (Node.js)

FROM node:24-alpine

RUN apk add --no-cache bash openssl libc6-compat

WORKDIR /app

# 1. Copiamos o package.json do common
COPY packages/common/package*.json ./packages/common/

# Entramos na pasta e instalamos as dependências (incluindo @prisma/client)
WORKDIR /app/packages/common
RUN npm install
# ---------------------

# Voltamos para a raiz e copiamos o resto do código do common
WORKDIR /app
COPY packages/common/ ./packages/common/

# 2. Copiamos os arquivos do serviço (Notification Service)
COPY services/notification-service/package*.json ./services/notification-service/
COPY services/notification-service/tsconfig.json ./services/notification-service/

# 3. Instalamos as dependências do serviço
WORKDIR /app/services/notification-service
RUN npm install

# 4. Linkamos o Prisma
RUN ln -s /app/packages/common/node_modules/.bin/prisma /usr/local/bin/prisma

# 5. Script de infra
COPY services/notification-service/wait-for-it.sh ./wait-for-it.sh
RUN chmod +x ./wait-for-it.sh

EXPOSE 3003
CMD ["npm", "run", "dev"]
