# Dockerfile.dev para Notification Service (Node.js)

FROM node:24-alpine

WORKDIR /app

RUN apk update && apk add --no-cache bash openssl libc6-compat

COPY services/notification-service/package*.json ./
COPY services/notification-service/tsconfig.json ./
COPY packages/common/package*.json ./packages/common/

RUN npm install

COPY services/notification-service/ .
COPY packages/common/ ./packages/common/

RUN chmod +x ./wait-for-it.sh
RUN find /app -type f -name "*.sh" -exec chmod +x {} \;

EXPOSE 3003

# CMD ["sh", "/app/wait-for-it.sh", "postgres:5432", "--", "npm", "run", "dev"]
