# Dockerfile.dev para API Gateway (Node.js)

FROM node:24-alpine

RUN apk add --no-cache bash openssl libc6-compat

WORKDIR /app

# 1. Copiamos o package.json do common
COPY packages/common/package*.json ./packages/common/

# Entramos na pasta e instalamos as dependências (incluindo @prisma/client)
WORKDIR /app/packages/common
RUN npm install
# ---------------------

# Voltamos para a raiz e copiamos o resto do código do common
WORKDIR /app
COPY packages/common/ ./packages/common/

# 2. Copiamos os arquivos do serviço (API Gateway)
COPY services/api-gateway-service/package*.json ./services/api-gateway-service/
COPY services/api-gateway-service/tsconfig.json ./services/api-gateway-service/

# 3. Instalamos as dependências do serviço
WORKDIR /app/services/api-gateway-service
RUN npm install

# 4. Linkamos o Prisma
RUN ln -s /app/packages/common/node_modules/.bin/prisma /usr/local/bin/prisma

# 5. Script de infra
COPY services/api-gateway-service/wait-for-it.sh ./wait-for-it.sh
RUN chmod +x ./wait-for-it.sh


EXPOSE 8080

# CMD ["sh", "-c", "./wait-for-it.sh auth-service:3000 -- npm run dev"]