# Dockerfile.dev para API Gateway (Node.js)

FROM node:24-alpine

WORKDIR /app

RUN apk update && apk add --no-cache bash openssl libc6-compat

COPY services/api-gateway-service/package*.json ./
COPY services/api-gateway-service/tsconfig.json ./
COPY packages/common/package*.json ./packages/common/

RUN npm install

COPY services/api-gateway-service/ .
COPY packages/common/ ./packages/common/

RUN chmod +x ./wait-for-it.sh
RUN find /app -type f -name "*.sh" -exec chmod +x {} \;

EXPOSE 8080

# CMD ["sh", "-c", "./wait-for-it.sh auth-service:3000 -- npm run dev"]